// reactjs/src/App.tsx
import CaseClient from "@casejs/case-client";
import "bulma/css/bulma.min.css";
import { useEffect, useState } from "react";

function App() {
  interface Pokemon {
    id: number;
    name: string;
    type: string;
    image: string;
  }

  const [pokemons, setPokemon] = useState<Pokemon[]>([]);

  useEffect(() => {
    const cs = new CaseClient();
    cs.from("pokemon")
      .find<Pokemon>()
      .then((res) => {
        setPokemon(res);
      });
  }, []);

  return (
    <div className="container">
      <div className="columns">
        <div className="column">
          <h1 className="title is-1">Svelte Starter for CASE</h1>
        </div>
      </div>

      <div className="columns">
        <div className="column">
          <p>This is a starter project for Svelte.</p>
        </div>
      </div>

      <div className="columns">
        <div className="column">
          <table className="table is-striped is-fullwidth">
            <thead>
              <tr>
                <th>Image</th>
                <th>ID</th>
                <th>Name</th>
                <th>Type</th>
              </tr>
            </thead>
            <tbody>
              {pokemons.map((pokemon) => (
                <tr>
                  <td>
                    <img src={pokemon.image} alt="{pokemon.name} image" />
                  </td>
                  <td>{pokemon.id}</td>
                  <td>{pokemon.name}</td>
                  <td>{pokemon.type}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

export default App;

// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import CaseClient from '@casejs/case-client';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'angular';
  pokemons: { id: number; name: string; type: string; image: string }[] = [];

  async ngOnInit() {
    const cs = new CaseClient();

    this.pokemons = await cs.from('pokemon').find();
  }
}

<div class="container">
  <div class="columns">
    <div class="column">
      <h1 class="title is-1">Angular Starter for CASE</h1>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <p>This is a starter project for Angular.</p>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <table class="table is-striped is-fullwidth">
        <thead>
          <tr>
            <th>Image</th>
            <th>ID</th>
            <th>Name</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let pokemon of pokemons">
            <td>
              <img src="{{ pokemon.image }}" alt="{{ pokemon.name }} image" />
            </td>
            <td>{{ pokemon.id }}</td>
            <td>{{ pokemon.name }}</td>
            <td>{{ pokemon.type }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
